using HistoricalGraphExplorer.Application.Interfaces;
using HistoricalGraphExplorer.Domain;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.AzureOpenAI;
using System.Text;
using System.Text.Json;

namespace HistoricalGraphExplorer.Application.Services;

/// <summary>
/// Copilot service using intent-based routing.
/// AI classifies intent → typed traversal → AI summarises clean DTOs.
/// No raw Gremlin is ever generated by AI.
/// </summary>
public class GraphCopilotService : IGraphCopilotService
{
    private readonly Kernel _kernel;
    private readonly IGraphTraversalService _traversal;
    private readonly ILogger<GraphCopilotService> _logger;

    // Compact schema — in system message only (not repeated per request)
    private const string SystemMessage = """
    You are a historical graph assistant. The graph contains ~780 historical events.
    Schema:
      Event: id=wd:Q<n>, name, startYear (int, negative=BCE), startTime (ISO)
      Participant: id=participant:<slug>, name  (slug = lowercase, hyphens)
      Place: id=place:<slug>, name
      Edges: Participant-[INVOLVED_IN]->Event, Event-[OCCURRED_AT]->Place

    Answer strictly using the provided records. If records are empty, say no data was found.
    Do not mention database internals, Gremlin, or graph concepts in your answer.
    """;

    public GraphCopilotService(Kernel kernel, IGraphTraversalService traversal, ILogger<GraphCopilotService> logger)
    {
        _kernel = kernel;
        _traversal = traversal;
        _logger = logger;
    }

    public async Task<string> AskAsync(string question)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();

        // Step 1: Classify intent
        var intent = await ClassifyIntentAsync(question);
        _logger.LogInformation("[Copilot] Intent={Intent} Participant={P} Place={Pl} From={F} To={T} EventId={E}",
            intent.Intent, intent.Participant, intent.Place, intent.FromYear, intent.ToYear, intent.EventId);

        // Step 2: Fetch data using typed traversal — no raw Gremlin
        var data = await FetchDataAsync(intent);

        if (string.IsNullOrWhiteSpace(data))
        {
            _logger.LogInformation("[Copilot] No records found for question={Q}", question);
            return "No matching records found in the graph for that question.";
        }

        // Step 3: AI summarises clean data
        var answer = await SummariseAsync(question, data);

        sw.Stop();
        _logger.LogInformation("[Copilot] Completed question={Q} ms={Ms}", question, sw.ElapsedMilliseconds);

        return answer;
    }

    // ── Intent Classification ─────────────────────────────────────────────────

    private async Task<QueryIntent> ClassifyIntentAsync(string question)
    {
        var prompt = $"""
        Classify the following historical question into exactly one JSON intent object.
        
        Intent types:
        - ParticipantQuery: asking about events involving a specific country/participant
        - PlaceQuery: asking about events at a specific location
        - YearRangeQuery: asking about events in a time period
        - EventDetailsQuery: asking about a specific named event
        
        Rules:
        - participant: lowercase hyphenated slug (e.g. "ottoman-empire")
        - place: lowercase hyphenated slug (e.g. "ukraine")
        - eventId: Wikidata id if known (e.g. "wd:Q74623"), else null
        - fromYear/toYear: integers, negative for BCE, null if not applicable
        - Return ONLY valid JSON, no markdown, no explanation.
        
        Examples:
        Q: "Which wars involved the Ottoman Empire?"
        → {{"intent":"ParticipantQuery","participant":"ottoman-empire","place":null,"eventId":null,"fromYear":null,"toYear":null}}
        
        Q: "What events took place in Ukraine?"
        → {{"intent":"PlaceQuery","participant":null,"place":"ukraine","eventId":null,"fromYear":null,"toYear":null}}
        
        Q: "List major battles between 1600 and 1700"
        → {{"intent":"YearRangeQuery","participant":null,"place":null,"eventId":null,"fromYear":1600,"toYear":1700}}
        
        Q: "What happened in the Great Turkish War?"
        → {{"intent":"EventDetailsQuery","participant":null,"place":null,"eventId":"wd:Q74623","fromYear":null,"toYear":null}}
        
        Question: {question}
        """;

        string raw;
        try
        {
            raw = (await _kernel.InvokePromptAsync(prompt,
                new KernelArguments(new AzureOpenAIPromptExecutionSettings { Temperature = 0.0 }))).ToString().Trim();
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[Copilot] Intent classification failed, using Unknown");
            return new QueryIntent(QueryIntentType.Unknown);
        }

        // Strip accidental markdown fences
        raw = raw.Replace("```json", "").Replace("```", "").Trim();

        try
        {
            var doc = JsonDocument.Parse(raw);
            var root = doc.RootElement;
            var intentStr = root.TryGetProperty("intent", out var iv) ? iv.GetString() : null;
            var intent = intentStr switch
            {
                "ParticipantQuery"  => QueryIntentType.ParticipantQuery,
                "PlaceQuery"        => QueryIntentType.PlaceQuery,
                "YearRangeQuery"    => QueryIntentType.YearRangeQuery,
                "EventDetailsQuery" => QueryIntentType.EventDetailsQuery,
                _                   => QueryIntentType.Unknown
            };

            return new QueryIntent(
                Intent:      intent,
                Participant: GetStringOrNull(root, "participant"),
                Place:       GetStringOrNull(root, "place"),
                EventId:     GetStringOrNull(root, "eventId"),
                FromYear:    GetIntOrNull(root, "fromYear"),
                ToYear:      GetIntOrNull(root, "toYear")
            );
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[Copilot] Failed to parse intent JSON: {Raw}", raw);
            return new QueryIntent(QueryIntentType.Unknown);
        }
    }

    // ── Data Fetching via Typed Traversal ────────────────────────────────────

    private async Task<string> FetchDataAsync(QueryIntent intent)
    {
        return intent.Intent switch
        {
            QueryIntentType.ParticipantQuery when !string.IsNullOrWhiteSpace(intent.Participant)
                => FormatEvents(await _traversal.GetEventsByParticipantAsync(intent.Participant!)),

            QueryIntentType.PlaceQuery when !string.IsNullOrWhiteSpace(intent.Place)
                => FormatEvents(await _traversal.GetEventsByPlaceAsync(intent.Place!)),

            QueryIntentType.YearRangeQuery
                => FormatEvents(await _traversal.GetEventsByYearRangeAsync(intent.FromYear, intent.ToYear)),

            QueryIntentType.EventDetailsQuery when !string.IsNullOrWhiteSpace(intent.EventId)
                => FormatEventDetails(await _traversal.GetEventDetailsAsync(intent.EventId!)),

            // Fallback: year range with no filter (return recent sample)
            _ => FormatEvents(await _traversal.GetEventsByYearRangeAsync(null, null, 50))
        };
    }

    // ── AI Summarisation ─────────────────────────────────────────────────────

    private async Task<string> SummariseAsync(string question, string data)
    {
        var prompt = $"""
        User question: {question}

        Graph records:
        {data}

        Answer the question using only the records above.
        List specific event names and years where relevant.
        If the records do not contain enough information, say so clearly.
        """;

        try
        {
            return (await _kernel.InvokePromptAsync(prompt,
                new KernelArguments(new AzureOpenAIPromptExecutionSettings { Temperature = 0.1 }))).ToString();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[Copilot] Summary call failed");
            return "⚠️ Could not generate a summary. Please try again.";
        }
    }

    // ── Formatters: Clean DTOs → Compact text for AI ─────────────────────────

    private static string FormatEvents(IReadOnlyCollection<EventVertex> events)
    {
        if (!events.Any()) return "";
        var sb = new StringBuilder();
        foreach (var e in events)
        {
            var year = e.StartYear.HasValue ? e.StartYear.Value.ToString() : "unknown year";
            sb.AppendLine($"- {e.Name} ({year})");
        }
        return sb.ToString();
    }

    private static string FormatEventDetails(EventDetails? details)
    {
        if (details is null) return "";
        var sb = new StringBuilder();
        sb.AppendLine($"Event: {details.Event.Name} ({details.Event.StartYear})");
        if (details.Participants.Any())
            sb.AppendLine($"Participants: {string.Join(", ", details.Participants)}");
        if (details.Places.Any())
            sb.AppendLine($"Places: {string.Join(", ", details.Places)}");
        return sb.ToString();
    }

    // ── JSON helpers ──────────────────────────────────────────────────────────

    private static string? GetStringOrNull(JsonElement el, string key)
        => el.TryGetProperty(key, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    private static int? GetIntOrNull(JsonElement el, string key)
    {
        if (!el.TryGetProperty(key, out var v)) return null;
        if (v.ValueKind == JsonValueKind.Number && v.TryGetInt32(out var i)) return i;
        return null;
    }
}
